[[groups]]
title = "Group A"
members = [
    { name = "Alice", email = "alice@example.com" },
    { name = "Bob", email = "bob@example.com" },
    { name = "Charlie", email = "charlie@example.com" },
    { name = "David", email = "david@example.com" },
    { name = "Eve", email = "eve@example.com" }
]

[[groups]]
title = "Group B"
members = [
    { name = "Frank", email = "frank@example.com" },
    { name = "Grace", email = "grace@example.com" },
    { name = "Hannah", email = "hannah@example.com" },
    { name = "Ivy", email = "ivy@example.com" },
    { name = "Jack", email = "jack@example.com" }
]